<?php
$this->headMeta()
		->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8')
		->appendHttpEquiv('Content-Language', 'ru-RU')
		->appendName('description', "Сервис оповещений о событиях для онлайн игры Сфера Судьбы." )
		->appendName('keywords', "Онлайн игра, Бот, Оповещения, Cфера Cудьбы, Destiny Sphere");

$version = $this->cacheVersion();

$this->headScript()->appendFile( "http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js");
$this->headScript()->appendFile( "/js/lib.js?{$version}");
$this->headLink()->prependStylesheet("/css/main.css?{$version}");
$this->headTitle("{$this->title}. dsBot - сервис оповещений о событиях для игры Сфера Судьбы (Destiny Sphere)");

echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->render('counters.phtml'); ?>
		<link rel="icon" href="/favicon.ico" type="image/x-icon"/>
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
		<?php echo $this->headLink(); ?>
	</head>
	<body>
		<div id="header" >
			<a href="/" id="logo"><img alt="логотип DSbot"  width="177px" height="66px" src="/img/dsbot.png"/></a>
			<div id="reg">
				<?php $this->MainMenu('auth'); ?>
			</div>
			<p id="describe">Сервис мониторинга красной кнопки</p>
			<div id="menus-block">
				<?php $this->MainMenu('main'); ?>
				<?php $this->MainMenu('profile'); ?>
			</div>
		</div>
		<div id="content">
			<?php echo $this->layout()->content; ?>
			<div class="clear"></div>
		</div>
		<div id="footer">
			&copy;2012 <span>Я! маленький апельсин</span><br/>
			<a href="mailto:support@dsbot.ru">support@dsbot.ru</a>
		</div>
		<?php $this->printCsrfToken(); ?>
		<?php echo $this->headScript(); ?>
	</body>
</html>
